#! /bin/bash

set -e

get_librarian_link()
{
    sed -ne 's/.*href="\(http:\/\/launchpadlibrarian.*\)".*/\1/p'
}

main()
{
    local p v
    local link
    local link_list=()
    local dpkg_list=()

    v="$UBUNTU_GCC_VERSION"
    for p in {gcc,cpp,g++}; do
        link=$(curl -s "https://launchpad.net/ubuntu/focal/amd64/$p/$v" | get_librarian_link)
        link_list+=("$link")
    done
    v="$UBUNTU_GCC9_VERSION"
    for p in {gcc-9,cpp-9,libgcc-9-dev,gcc-9-base,g++-9,libstdc++-9-dev,libasan5}; do
        link=$(curl -s "https://launchpad.net/ubuntu/focal/amd64/$p/$v" | get_librarian_link)
        link_list+=("$link")
    done

    curl_cmd=(curl -q -Z)
    for link in "${link_list[@]}"; do
        curl_cmd+=(-O "$link")
        dpkg_list+=(./"$(basename "$link")")
    done
    "${curl_cmd[@]}"
    apt-get install -y --no-install-recommends "${dpkg_list[@]}"
}

main "$@"
